#!/bin/bash

presc_min=1
presc_max=32768
hz=1000

preamble() {
	cat << EOF
//
// Generated by ${0} on $(date)
//
// This script finds the value for an F_RTT_OSC prescaler that will get G_freq_RTTCLK
// somewhere in the neighborhood of ${hz}Hz
//
// The macro F_RTT_OSC must be set before calling
// The macros G_freq_RTTCLK, RTC_PRESCALER_1KHz_DIV_gc, and RTC_PERIOD_1KHz_CYC_gc are set
// when done
#undef _BEST_DIFF
#define _BEST_DIFF (F_RTT_OSC+1)

#ifndef F_RTT_OSC
# error "F_RTT_OSC not set"
#endif
EOF
}

test_body() {
	PSC="${1}"

	cat << EOF

#if (F_RTT_OSC / ${PSC}UL > ${hz}UL && (F_RTT_OSC / ${PSC}UL) - ${hz}UL < _BEST_DIFF) || (F_RTT_OSC / ${PSC}UL <= ${hz}UL && ${hz}UL - (F_RTT_OSC / ${PSC}UL) < _BEST_DIFF)
# undef RTC_PRESCALER_DIV_gc
# undef G_freq_RTTCLK
# undef _BEST_DIFF
# define RTC_PRESCALER_1KHz_DIV_gc RTC_PRESCALER_DIV${PSC}_gc
# define RTC_PERIOD_1KHz_CYC_gc RTC_PERIOD_CYC${PSC}_gc
# define G_freq_RTTCLK (F_RTT_OSC / ${PSC}UL)
# if G_freq_RTTCLK > ${hz}
#  define _BEST_DIFF (G_freq_RTTCLK - ${hz}UL)
# else
#  define _BEST_DIFF (${hz}UL - G_freq_RTTCLK)
# endif
#endif
EOF
}

postamble() {
	cat << EOF
#undef _BEST_DIFF
EOF
}

preamble
presc=${presc_min}
while ((presc <= presc_max)); do
	test_body "${presc}"
	((presc *= 2))
done
postamble
