// SPDX-License-Identifier: GPL-3.0-only
/***********************************************************************
*                                                                      *
*                                                                      *
* Copyright 2021, 2024 svijsv                                          *
* This program is free software: you can redistribute it and/or modify *
* it under the terms of the GNU General Public License as published by *
* the Free Software Foundation, version 3.                             *
*                                                                      *
* This program is distributed in the hope that it will be useful, but  *
* WITHOUT ANY WARRANTY; without even the implied warranty of           *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU    *
* General Public License for more details.                             *
*                                                                      *
* You should have received a copy of the GNU General Public License    *
* along with this program.  If not, see <http:// www.gnu.org/licenses/>.*
*                                                                      *
*                                                                      *
***********************************************************************/
// platform_base_pins.h
// Platform-specific shim for the frontend
// NOTES:
//   This file is for defining the base pin IDs without cluttering platform.h
//   and should only be included by platform.h
//
//   There are sections of code (like pin interrupt setting) that depend on the
//   port numbers being consecutive (e.g. A = 1, C = 3, etc)
//

typedef uint_fast16_t gpio_pin_t;

//
// IO bit masks
//
// 4 bits (16 possible pins)
#define GPIO_PIN_OFFSET 0U
#define GPIO_PIN_MASK  (0b1111U << GPIO_PIN_OFFSET)
//
// 4 bits, can't be 0 (15 possible ports)
#define GPIO_PORT_OFFSET 4U
#define GPIO_PORT_MASK (0b1111U << GPIO_PORT_OFFSET)
//
// 3 bits
#define GPIO_CTRL_OFFSET 8U
#define GPIO_CTRL_MASK (0b111U << GPIO_BIAS_OFFSET)

//#define GPIO_PIN_IS_VALID(_pin_) (PINID(_pin_) != 0 && GPIO_GET_PINNO(_pin_) <= 15)
//#define GPIO_PIN_IS_VALID(_pin_) (PINID(_pin_) != 0)
#define GPIO_PIN_IS_VALID(_pin_) (((_pin_) & GPIO_PORT_MASK) != 0)


//
// Generated by platform_base_pins.sh on Sat Aug 31 08:19:03 PM EDT 2024
//

#ifndef HAVE_GPIO_PORT_DEFAULT
# define HAVE_GPIO_PORT_DEFAULT 0
#endif

//
// Port A
#ifndef HAVE_GPIO_PORTA
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOA)
#  define HAVE_GPIO_PORTA 1
# else
#  define HAVE_GPIO_PORTA 0
# endif
#endif
#if HAVE_GPIO_PORTA
# define GPIO_PORTA 1U
# define GPIO_PORTA_MASK (GPIO_PORTA << GPIO_PORT_OFFSET)
# define PINID_A0  (GPIO_PORTA_MASK | 0x00U)
# define PINID_A1  (GPIO_PORTA_MASK | 0x01U)
# define PINID_A2  (GPIO_PORTA_MASK | 0x02U)
# define PINID_A3  (GPIO_PORTA_MASK | 0x03U)
# define PINID_A4  (GPIO_PORTA_MASK | 0x04U)
# define PINID_A5  (GPIO_PORTA_MASK | 0x05U)
# define PINID_A6  (GPIO_PORTA_MASK | 0x06U)
# define PINID_A7  (GPIO_PORTA_MASK | 0x07U)
# define PINID_A8  (GPIO_PORTA_MASK | 0x08U)
# define PINID_A9  (GPIO_PORTA_MASK | 0x09U)
# define PINID_A10 (GPIO_PORTA_MASK | 0x0AU)
# define PINID_A11 (GPIO_PORTA_MASK | 0x0BU)
# define PINID_A12 (GPIO_PORTA_MASK | 0x0CU)
# define PINID_A13 (GPIO_PORTA_MASK | 0x0DU)
# define PINID_A14 (GPIO_PORTA_MASK | 0x0EU)
# define PINID_A15 (GPIO_PORTA_MASK | 0x0FU)
#else
# define GPIO_PORTA 0U
# define GPIO_PORTA_MASK 0U
# define PINID_A0  0U
# define PINID_A1  0U
# define PINID_A2  0U
# define PINID_A3  0U
# define PINID_A4  0U
# define PINID_A5  0U
# define PINID_A6  0U
# define PINID_A7  0U
# define PINID_A8  0U
# define PINID_A9  0U
# define PINID_A10 0U
# define PINID_A11 0U
# define PINID_A12 0U
# define PINID_A13 0U
# define PINID_A14 0U
# define PINID_A15 0U
#endif

//
// Port B
#ifndef HAVE_GPIO_PORTB
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOB)
#  define HAVE_GPIO_PORTB 1
# else
#  define HAVE_GPIO_PORTB 0
# endif
#endif
#if HAVE_GPIO_PORTB
# define GPIO_PORTB 2U
# define GPIO_PORTB_MASK (GPIO_PORTB << GPIO_PORT_OFFSET)
# define PINID_B0  (GPIO_PORTB_MASK | 0x00U)
# define PINID_B1  (GPIO_PORTB_MASK | 0x01U)
# define PINID_B2  (GPIO_PORTB_MASK | 0x02U)
# define PINID_B3  (GPIO_PORTB_MASK | 0x03U)
# define PINID_B4  (GPIO_PORTB_MASK | 0x04U)
# define PINID_B5  (GPIO_PORTB_MASK | 0x05U)
# define PINID_B6  (GPIO_PORTB_MASK | 0x06U)
# define PINID_B7  (GPIO_PORTB_MASK | 0x07U)
# define PINID_B8  (GPIO_PORTB_MASK | 0x08U)
# define PINID_B9  (GPIO_PORTB_MASK | 0x09U)
# define PINID_B10 (GPIO_PORTB_MASK | 0x0AU)
# define PINID_B11 (GPIO_PORTB_MASK | 0x0BU)
# define PINID_B12 (GPIO_PORTB_MASK | 0x0CU)
# define PINID_B13 (GPIO_PORTB_MASK | 0x0DU)
# define PINID_B14 (GPIO_PORTB_MASK | 0x0EU)
# define PINID_B15 (GPIO_PORTB_MASK | 0x0FU)
#else
# define GPIO_PORTB 0U
# define GPIO_PORTB_MASK 0U
# define PINID_B0  0U
# define PINID_B1  0U
# define PINID_B2  0U
# define PINID_B3  0U
# define PINID_B4  0U
# define PINID_B5  0U
# define PINID_B6  0U
# define PINID_B7  0U
# define PINID_B8  0U
# define PINID_B9  0U
# define PINID_B10 0U
# define PINID_B11 0U
# define PINID_B12 0U
# define PINID_B13 0U
# define PINID_B14 0U
# define PINID_B15 0U
#endif

//
// Port C
#ifndef HAVE_GPIO_PORTC
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOC)
#  define HAVE_GPIO_PORTC 1
# else
#  define HAVE_GPIO_PORTC 0
# endif
#endif
#if HAVE_GPIO_PORTC
# define GPIO_PORTC 3U
# define GPIO_PORTC_MASK (GPIO_PORTC << GPIO_PORT_OFFSET)
# define PINID_C0  (GPIO_PORTC_MASK | 0x00U)
# define PINID_C1  (GPIO_PORTC_MASK | 0x01U)
# define PINID_C2  (GPIO_PORTC_MASK | 0x02U)
# define PINID_C3  (GPIO_PORTC_MASK | 0x03U)
# define PINID_C4  (GPIO_PORTC_MASK | 0x04U)
# define PINID_C5  (GPIO_PORTC_MASK | 0x05U)
# define PINID_C6  (GPIO_PORTC_MASK | 0x06U)
# define PINID_C7  (GPIO_PORTC_MASK | 0x07U)
# define PINID_C8  (GPIO_PORTC_MASK | 0x08U)
# define PINID_C9  (GPIO_PORTC_MASK | 0x09U)
# define PINID_C10 (GPIO_PORTC_MASK | 0x0AU)
# define PINID_C11 (GPIO_PORTC_MASK | 0x0BU)
# define PINID_C12 (GPIO_PORTC_MASK | 0x0CU)
# define PINID_C13 (GPIO_PORTC_MASK | 0x0DU)
# define PINID_C14 (GPIO_PORTC_MASK | 0x0EU)
# define PINID_C15 (GPIO_PORTC_MASK | 0x0FU)
#else
# define GPIO_PORTC 0U
# define GPIO_PORTC_MASK 0U
# define PINID_C0  0U
# define PINID_C1  0U
# define PINID_C2  0U
# define PINID_C3  0U
# define PINID_C4  0U
# define PINID_C5  0U
# define PINID_C6  0U
# define PINID_C7  0U
# define PINID_C8  0U
# define PINID_C9  0U
# define PINID_C10 0U
# define PINID_C11 0U
# define PINID_C12 0U
# define PINID_C13 0U
# define PINID_C14 0U
# define PINID_C15 0U
#endif

//
// Port D
#ifndef HAVE_GPIO_PORTD
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOD)
#  define HAVE_GPIO_PORTD 1
# else
#  define HAVE_GPIO_PORTD 0
# endif
#endif
#if HAVE_GPIO_PORTD
# define GPIO_PORTD 4U
# define GPIO_PORTD_MASK (GPIO_PORTD << GPIO_PORT_OFFSET)
# define PINID_D0  (GPIO_PORTD_MASK | 0x00U)
# define PINID_D1  (GPIO_PORTD_MASK | 0x01U)
# define PINID_D2  (GPIO_PORTD_MASK | 0x02U)
# define PINID_D3  (GPIO_PORTD_MASK | 0x03U)
# define PINID_D4  (GPIO_PORTD_MASK | 0x04U)
# define PINID_D5  (GPIO_PORTD_MASK | 0x05U)
# define PINID_D6  (GPIO_PORTD_MASK | 0x06U)
# define PINID_D7  (GPIO_PORTD_MASK | 0x07U)
# define PINID_D8  (GPIO_PORTD_MASK | 0x08U)
# define PINID_D9  (GPIO_PORTD_MASK | 0x09U)
# define PINID_D10 (GPIO_PORTD_MASK | 0x0AU)
# define PINID_D11 (GPIO_PORTD_MASK | 0x0BU)
# define PINID_D12 (GPIO_PORTD_MASK | 0x0CU)
# define PINID_D13 (GPIO_PORTD_MASK | 0x0DU)
# define PINID_D14 (GPIO_PORTD_MASK | 0x0EU)
# define PINID_D15 (GPIO_PORTD_MASK | 0x0FU)
#else
# define GPIO_PORTD 0U
# define GPIO_PORTD_MASK 0U
# define PINID_D0  0U
# define PINID_D1  0U
# define PINID_D2  0U
# define PINID_D3  0U
# define PINID_D4  0U
# define PINID_D5  0U
# define PINID_D6  0U
# define PINID_D7  0U
# define PINID_D8  0U
# define PINID_D9  0U
# define PINID_D10 0U
# define PINID_D11 0U
# define PINID_D12 0U
# define PINID_D13 0U
# define PINID_D14 0U
# define PINID_D15 0U
#endif

//
// Port E
#ifndef HAVE_GPIO_PORTE
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOE)
#  define HAVE_GPIO_PORTE 1
# else
#  define HAVE_GPIO_PORTE 0
# endif
#endif
#if HAVE_GPIO_PORTE
# define GPIO_PORTE 5U
# define GPIO_PORTE_MASK (GPIO_PORTE << GPIO_PORT_OFFSET)
# define PINID_E0  (GPIO_PORTE_MASK | 0x00U)
# define PINID_E1  (GPIO_PORTE_MASK | 0x01U)
# define PINID_E2  (GPIO_PORTE_MASK | 0x02U)
# define PINID_E3  (GPIO_PORTE_MASK | 0x03U)
# define PINID_E4  (GPIO_PORTE_MASK | 0x04U)
# define PINID_E5  (GPIO_PORTE_MASK | 0x05U)
# define PINID_E6  (GPIO_PORTE_MASK | 0x06U)
# define PINID_E7  (GPIO_PORTE_MASK | 0x07U)
# define PINID_E8  (GPIO_PORTE_MASK | 0x08U)
# define PINID_E9  (GPIO_PORTE_MASK | 0x09U)
# define PINID_E10 (GPIO_PORTE_MASK | 0x0AU)
# define PINID_E11 (GPIO_PORTE_MASK | 0x0BU)
# define PINID_E12 (GPIO_PORTE_MASK | 0x0CU)
# define PINID_E13 (GPIO_PORTE_MASK | 0x0DU)
# define PINID_E14 (GPIO_PORTE_MASK | 0x0EU)
# define PINID_E15 (GPIO_PORTE_MASK | 0x0FU)
#else
# define GPIO_PORTE 0U
# define GPIO_PORTE_MASK 0U
# define PINID_E0  0U
# define PINID_E1  0U
# define PINID_E2  0U
# define PINID_E3  0U
# define PINID_E4  0U
# define PINID_E5  0U
# define PINID_E6  0U
# define PINID_E7  0U
# define PINID_E8  0U
# define PINID_E9  0U
# define PINID_E10 0U
# define PINID_E11 0U
# define PINID_E12 0U
# define PINID_E13 0U
# define PINID_E14 0U
# define PINID_E15 0U
#endif

//
// Port F
#ifndef HAVE_GPIO_PORTF
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOF)
#  define HAVE_GPIO_PORTF 1
# else
#  define HAVE_GPIO_PORTF 0
# endif
#endif
#if HAVE_GPIO_PORTF
# define GPIO_PORTF 6U
# define GPIO_PORTF_MASK (GPIO_PORTF << GPIO_PORT_OFFSET)
# define PINID_F0  (GPIO_PORTF_MASK | 0x00U)
# define PINID_F1  (GPIO_PORTF_MASK | 0x01U)
# define PINID_F2  (GPIO_PORTF_MASK | 0x02U)
# define PINID_F3  (GPIO_PORTF_MASK | 0x03U)
# define PINID_F4  (GPIO_PORTF_MASK | 0x04U)
# define PINID_F5  (GPIO_PORTF_MASK | 0x05U)
# define PINID_F6  (GPIO_PORTF_MASK | 0x06U)
# define PINID_F7  (GPIO_PORTF_MASK | 0x07U)
# define PINID_F8  (GPIO_PORTF_MASK | 0x08U)
# define PINID_F9  (GPIO_PORTF_MASK | 0x09U)
# define PINID_F10 (GPIO_PORTF_MASK | 0x0AU)
# define PINID_F11 (GPIO_PORTF_MASK | 0x0BU)
# define PINID_F12 (GPIO_PORTF_MASK | 0x0CU)
# define PINID_F13 (GPIO_PORTF_MASK | 0x0DU)
# define PINID_F14 (GPIO_PORTF_MASK | 0x0EU)
# define PINID_F15 (GPIO_PORTF_MASK | 0x0FU)
#else
# define GPIO_PORTF 0U
# define GPIO_PORTF_MASK 0U
# define PINID_F0  0U
# define PINID_F1  0U
# define PINID_F2  0U
# define PINID_F3  0U
# define PINID_F4  0U
# define PINID_F5  0U
# define PINID_F6  0U
# define PINID_F7  0U
# define PINID_F8  0U
# define PINID_F9  0U
# define PINID_F10 0U
# define PINID_F11 0U
# define PINID_F12 0U
# define PINID_F13 0U
# define PINID_F14 0U
# define PINID_F15 0U
#endif

//
// Port G
#ifndef HAVE_GPIO_PORTG
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOG)
#  define HAVE_GPIO_PORTG 1
# else
#  define HAVE_GPIO_PORTG 0
# endif
#endif
#if HAVE_GPIO_PORTG
# define GPIO_PORTG 7U
# define GPIO_PORTG_MASK (GPIO_PORTG << GPIO_PORT_OFFSET)
# define PINID_G0  (GPIO_PORTG_MASK | 0x00U)
# define PINID_G1  (GPIO_PORTG_MASK | 0x01U)
# define PINID_G2  (GPIO_PORTG_MASK | 0x02U)
# define PINID_G3  (GPIO_PORTG_MASK | 0x03U)
# define PINID_G4  (GPIO_PORTG_MASK | 0x04U)
# define PINID_G5  (GPIO_PORTG_MASK | 0x05U)
# define PINID_G6  (GPIO_PORTG_MASK | 0x06U)
# define PINID_G7  (GPIO_PORTG_MASK | 0x07U)
# define PINID_G8  (GPIO_PORTG_MASK | 0x08U)
# define PINID_G9  (GPIO_PORTG_MASK | 0x09U)
# define PINID_G10 (GPIO_PORTG_MASK | 0x0AU)
# define PINID_G11 (GPIO_PORTG_MASK | 0x0BU)
# define PINID_G12 (GPIO_PORTG_MASK | 0x0CU)
# define PINID_G13 (GPIO_PORTG_MASK | 0x0DU)
# define PINID_G14 (GPIO_PORTG_MASK | 0x0EU)
# define PINID_G15 (GPIO_PORTG_MASK | 0x0FU)
#else
# define GPIO_PORTG 0U
# define GPIO_PORTG_MASK 0U
# define PINID_G0  0U
# define PINID_G1  0U
# define PINID_G2  0U
# define PINID_G3  0U
# define PINID_G4  0U
# define PINID_G5  0U
# define PINID_G6  0U
# define PINID_G7  0U
# define PINID_G8  0U
# define PINID_G9  0U
# define PINID_G10 0U
# define PINID_G11 0U
# define PINID_G12 0U
# define PINID_G13 0U
# define PINID_G14 0U
# define PINID_G15 0U
#endif

//
// Port H
#ifndef HAVE_GPIO_PORTH
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOH)
#  define HAVE_GPIO_PORTH 1
# else
#  define HAVE_GPIO_PORTH 0
# endif
#endif
#if HAVE_GPIO_PORTH
# define GPIO_PORTH 8U
# define GPIO_PORTH_MASK (GPIO_PORTH << GPIO_PORT_OFFSET)
# define PINID_H0  (GPIO_PORTH_MASK | 0x00U)
# define PINID_H1  (GPIO_PORTH_MASK | 0x01U)
# define PINID_H2  (GPIO_PORTH_MASK | 0x02U)
# define PINID_H3  (GPIO_PORTH_MASK | 0x03U)
# define PINID_H4  (GPIO_PORTH_MASK | 0x04U)
# define PINID_H5  (GPIO_PORTH_MASK | 0x05U)
# define PINID_H6  (GPIO_PORTH_MASK | 0x06U)
# define PINID_H7  (GPIO_PORTH_MASK | 0x07U)
# define PINID_H8  (GPIO_PORTH_MASK | 0x08U)
# define PINID_H9  (GPIO_PORTH_MASK | 0x09U)
# define PINID_H10 (GPIO_PORTH_MASK | 0x0AU)
# define PINID_H11 (GPIO_PORTH_MASK | 0x0BU)
# define PINID_H12 (GPIO_PORTH_MASK | 0x0CU)
# define PINID_H13 (GPIO_PORTH_MASK | 0x0DU)
# define PINID_H14 (GPIO_PORTH_MASK | 0x0EU)
# define PINID_H15 (GPIO_PORTH_MASK | 0x0FU)
#else
# define GPIO_PORTH 0U
# define GPIO_PORTH_MASK 0U
# define PINID_H0  0U
# define PINID_H1  0U
# define PINID_H2  0U
# define PINID_H3  0U
# define PINID_H4  0U
# define PINID_H5  0U
# define PINID_H6  0U
# define PINID_H7  0U
# define PINID_H8  0U
# define PINID_H9  0U
# define PINID_H10 0U
# define PINID_H11 0U
# define PINID_H12 0U
# define PINID_H13 0U
# define PINID_H14 0U
# define PINID_H15 0U
#endif

//
// Port I
#ifndef HAVE_GPIO_PORTI
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOI)
#  define HAVE_GPIO_PORTI 1
# else
#  define HAVE_GPIO_PORTI 0
# endif
#endif
#if HAVE_GPIO_PORTI
# define GPIO_PORTI 9U
# define GPIO_PORTI_MASK (GPIO_PORTI << GPIO_PORT_OFFSET)
# define PINID_I0  (GPIO_PORTI_MASK | 0x00U)
# define PINID_I1  (GPIO_PORTI_MASK | 0x01U)
# define PINID_I2  (GPIO_PORTI_MASK | 0x02U)
# define PINID_I3  (GPIO_PORTI_MASK | 0x03U)
# define PINID_I4  (GPIO_PORTI_MASK | 0x04U)
# define PINID_I5  (GPIO_PORTI_MASK | 0x05U)
# define PINID_I6  (GPIO_PORTI_MASK | 0x06U)
# define PINID_I7  (GPIO_PORTI_MASK | 0x07U)
# define PINID_I8  (GPIO_PORTI_MASK | 0x08U)
# define PINID_I9  (GPIO_PORTI_MASK | 0x09U)
# define PINID_I10 (GPIO_PORTI_MASK | 0x0AU)
# define PINID_I11 (GPIO_PORTI_MASK | 0x0BU)
# define PINID_I12 (GPIO_PORTI_MASK | 0x0CU)
# define PINID_I13 (GPIO_PORTI_MASK | 0x0DU)
# define PINID_I14 (GPIO_PORTI_MASK | 0x0EU)
# define PINID_I15 (GPIO_PORTI_MASK | 0x0FU)
#else
# define GPIO_PORTI 0U
# define GPIO_PORTI_MASK 0U
# define PINID_I0  0U
# define PINID_I1  0U
# define PINID_I2  0U
# define PINID_I3  0U
# define PINID_I4  0U
# define PINID_I5  0U
# define PINID_I6  0U
# define PINID_I7  0U
# define PINID_I8  0U
# define PINID_I9  0U
# define PINID_I10 0U
# define PINID_I11 0U
# define PINID_I12 0U
# define PINID_I13 0U
# define PINID_I14 0U
# define PINID_I15 0U
#endif

//
// Port J
#ifndef HAVE_GPIO_PORTJ
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOJ)
#  define HAVE_GPIO_PORTJ 1
# else
#  define HAVE_GPIO_PORTJ 0
# endif
#endif
#if HAVE_GPIO_PORTJ
# define GPIO_PORTJ 10U
# define GPIO_PORTJ_MASK (GPIO_PORTJ << GPIO_PORT_OFFSET)
# define PINID_J0  (GPIO_PORTJ_MASK | 0x00U)
# define PINID_J1  (GPIO_PORTJ_MASK | 0x01U)
# define PINID_J2  (GPIO_PORTJ_MASK | 0x02U)
# define PINID_J3  (GPIO_PORTJ_MASK | 0x03U)
# define PINID_J4  (GPIO_PORTJ_MASK | 0x04U)
# define PINID_J5  (GPIO_PORTJ_MASK | 0x05U)
# define PINID_J6  (GPIO_PORTJ_MASK | 0x06U)
# define PINID_J7  (GPIO_PORTJ_MASK | 0x07U)
# define PINID_J8  (GPIO_PORTJ_MASK | 0x08U)
# define PINID_J9  (GPIO_PORTJ_MASK | 0x09U)
# define PINID_J10 (GPIO_PORTJ_MASK | 0x0AU)
# define PINID_J11 (GPIO_PORTJ_MASK | 0x0BU)
# define PINID_J12 (GPIO_PORTJ_MASK | 0x0CU)
# define PINID_J13 (GPIO_PORTJ_MASK | 0x0DU)
# define PINID_J14 (GPIO_PORTJ_MASK | 0x0EU)
# define PINID_J15 (GPIO_PORTJ_MASK | 0x0FU)
#else
# define GPIO_PORTJ 0U
# define GPIO_PORTJ_MASK 0U
# define PINID_J0  0U
# define PINID_J1  0U
# define PINID_J2  0U
# define PINID_J3  0U
# define PINID_J4  0U
# define PINID_J5  0U
# define PINID_J6  0U
# define PINID_J7  0U
# define PINID_J8  0U
# define PINID_J9  0U
# define PINID_J10 0U
# define PINID_J11 0U
# define PINID_J12 0U
# define PINID_J13 0U
# define PINID_J14 0U
# define PINID_J15 0U
#endif

//
// Port K
#ifndef HAVE_GPIO_PORTK
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOK)
#  define HAVE_GPIO_PORTK 1
# else
#  define HAVE_GPIO_PORTK 0
# endif
#endif
#if HAVE_GPIO_PORTK
# define GPIO_PORTK 11U
# define GPIO_PORTK_MASK (GPIO_PORTK << GPIO_PORT_OFFSET)
# define PINID_K0  (GPIO_PORTK_MASK | 0x00U)
# define PINID_K1  (GPIO_PORTK_MASK | 0x01U)
# define PINID_K2  (GPIO_PORTK_MASK | 0x02U)
# define PINID_K3  (GPIO_PORTK_MASK | 0x03U)
# define PINID_K4  (GPIO_PORTK_MASK | 0x04U)
# define PINID_K5  (GPIO_PORTK_MASK | 0x05U)
# define PINID_K6  (GPIO_PORTK_MASK | 0x06U)
# define PINID_K7  (GPIO_PORTK_MASK | 0x07U)
# define PINID_K8  (GPIO_PORTK_MASK | 0x08U)
# define PINID_K9  (GPIO_PORTK_MASK | 0x09U)
# define PINID_K10 (GPIO_PORTK_MASK | 0x0AU)
# define PINID_K11 (GPIO_PORTK_MASK | 0x0BU)
# define PINID_K12 (GPIO_PORTK_MASK | 0x0CU)
# define PINID_K13 (GPIO_PORTK_MASK | 0x0DU)
# define PINID_K14 (GPIO_PORTK_MASK | 0x0EU)
# define PINID_K15 (GPIO_PORTK_MASK | 0x0FU)
#else
# define GPIO_PORTK 0U
# define GPIO_PORTK_MASK 0U
# define PINID_K0  0U
# define PINID_K1  0U
# define PINID_K2  0U
# define PINID_K3  0U
# define PINID_K4  0U
# define PINID_K5  0U
# define PINID_K6  0U
# define PINID_K7  0U
# define PINID_K8  0U
# define PINID_K9  0U
# define PINID_K10 0U
# define PINID_K11 0U
# define PINID_K12 0U
# define PINID_K13 0U
# define PINID_K14 0U
# define PINID_K15 0U
#endif

//
// Port L
#ifndef HAVE_GPIO_PORTL
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOL)
#  define HAVE_GPIO_PORTL 1
# else
#  define HAVE_GPIO_PORTL 0
# endif
#endif
#if HAVE_GPIO_PORTL
# define GPIO_PORTL 12U
# define GPIO_PORTL_MASK (GPIO_PORTL << GPIO_PORT_OFFSET)
# define PINID_L0  (GPIO_PORTL_MASK | 0x00U)
# define PINID_L1  (GPIO_PORTL_MASK | 0x01U)
# define PINID_L2  (GPIO_PORTL_MASK | 0x02U)
# define PINID_L3  (GPIO_PORTL_MASK | 0x03U)
# define PINID_L4  (GPIO_PORTL_MASK | 0x04U)
# define PINID_L5  (GPIO_PORTL_MASK | 0x05U)
# define PINID_L6  (GPIO_PORTL_MASK | 0x06U)
# define PINID_L7  (GPIO_PORTL_MASK | 0x07U)
# define PINID_L8  (GPIO_PORTL_MASK | 0x08U)
# define PINID_L9  (GPIO_PORTL_MASK | 0x09U)
# define PINID_L10 (GPIO_PORTL_MASK | 0x0AU)
# define PINID_L11 (GPIO_PORTL_MASK | 0x0BU)
# define PINID_L12 (GPIO_PORTL_MASK | 0x0CU)
# define PINID_L13 (GPIO_PORTL_MASK | 0x0DU)
# define PINID_L14 (GPIO_PORTL_MASK | 0x0EU)
# define PINID_L15 (GPIO_PORTL_MASK | 0x0FU)
#else
# define GPIO_PORTL 0U
# define GPIO_PORTL_MASK 0U
# define PINID_L0  0U
# define PINID_L1  0U
# define PINID_L2  0U
# define PINID_L3  0U
# define PINID_L4  0U
# define PINID_L5  0U
# define PINID_L6  0U
# define PINID_L7  0U
# define PINID_L8  0U
# define PINID_L9  0U
# define PINID_L10 0U
# define PINID_L11 0U
# define PINID_L12 0U
# define PINID_L13 0U
# define PINID_L14 0U
# define PINID_L15 0U
#endif

//
// Port M
#ifndef HAVE_GPIO_PORTM
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOM)
#  define HAVE_GPIO_PORTM 1
# else
#  define HAVE_GPIO_PORTM 0
# endif
#endif
#if HAVE_GPIO_PORTM
# define GPIO_PORTM 13U
# define GPIO_PORTM_MASK (GPIO_PORTM << GPIO_PORT_OFFSET)
# define PINID_M0  (GPIO_PORTM_MASK | 0x00U)
# define PINID_M1  (GPIO_PORTM_MASK | 0x01U)
# define PINID_M2  (GPIO_PORTM_MASK | 0x02U)
# define PINID_M3  (GPIO_PORTM_MASK | 0x03U)
# define PINID_M4  (GPIO_PORTM_MASK | 0x04U)
# define PINID_M5  (GPIO_PORTM_MASK | 0x05U)
# define PINID_M6  (GPIO_PORTM_MASK | 0x06U)
# define PINID_M7  (GPIO_PORTM_MASK | 0x07U)
# define PINID_M8  (GPIO_PORTM_MASK | 0x08U)
# define PINID_M9  (GPIO_PORTM_MASK | 0x09U)
# define PINID_M10 (GPIO_PORTM_MASK | 0x0AU)
# define PINID_M11 (GPIO_PORTM_MASK | 0x0BU)
# define PINID_M12 (GPIO_PORTM_MASK | 0x0CU)
# define PINID_M13 (GPIO_PORTM_MASK | 0x0DU)
# define PINID_M14 (GPIO_PORTM_MASK | 0x0EU)
# define PINID_M15 (GPIO_PORTM_MASK | 0x0FU)
#else
# define GPIO_PORTM 0U
# define GPIO_PORTM_MASK 0U
# define PINID_M0  0U
# define PINID_M1  0U
# define PINID_M2  0U
# define PINID_M3  0U
# define PINID_M4  0U
# define PINID_M5  0U
# define PINID_M6  0U
# define PINID_M7  0U
# define PINID_M8  0U
# define PINID_M9  0U
# define PINID_M10 0U
# define PINID_M11 0U
# define PINID_M12 0U
# define PINID_M13 0U
# define PINID_M14 0U
# define PINID_M15 0U
#endif

//
// Port N
#ifndef HAVE_GPIO_PORTN
# if HAVE_GPIO_PORT_DEFAULT && defined(GPION)
#  define HAVE_GPIO_PORTN 1
# else
#  define HAVE_GPIO_PORTN 0
# endif
#endif
#if HAVE_GPIO_PORTN
# define GPIO_PORTN 14U
# define GPIO_PORTN_MASK (GPIO_PORTN << GPIO_PORT_OFFSET)
# define PINID_N0  (GPIO_PORTN_MASK | 0x00U)
# define PINID_N1  (GPIO_PORTN_MASK | 0x01U)
# define PINID_N2  (GPIO_PORTN_MASK | 0x02U)
# define PINID_N3  (GPIO_PORTN_MASK | 0x03U)
# define PINID_N4  (GPIO_PORTN_MASK | 0x04U)
# define PINID_N5  (GPIO_PORTN_MASK | 0x05U)
# define PINID_N6  (GPIO_PORTN_MASK | 0x06U)
# define PINID_N7  (GPIO_PORTN_MASK | 0x07U)
# define PINID_N8  (GPIO_PORTN_MASK | 0x08U)
# define PINID_N9  (GPIO_PORTN_MASK | 0x09U)
# define PINID_N10 (GPIO_PORTN_MASK | 0x0AU)
# define PINID_N11 (GPIO_PORTN_MASK | 0x0BU)
# define PINID_N12 (GPIO_PORTN_MASK | 0x0CU)
# define PINID_N13 (GPIO_PORTN_MASK | 0x0DU)
# define PINID_N14 (GPIO_PORTN_MASK | 0x0EU)
# define PINID_N15 (GPIO_PORTN_MASK | 0x0FU)
#else
# define GPIO_PORTN 0U
# define GPIO_PORTN_MASK 0U
# define PINID_N0  0U
# define PINID_N1  0U
# define PINID_N2  0U
# define PINID_N3  0U
# define PINID_N4  0U
# define PINID_N5  0U
# define PINID_N6  0U
# define PINID_N7  0U
# define PINID_N8  0U
# define PINID_N9  0U
# define PINID_N10 0U
# define PINID_N11 0U
# define PINID_N12 0U
# define PINID_N13 0U
# define PINID_N14 0U
# define PINID_N15 0U
#endif

//
// Port O
#ifndef HAVE_GPIO_PORTO
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIOO)
#  define HAVE_GPIO_PORTO 1
# else
#  define HAVE_GPIO_PORTO 0
# endif
#endif
#if HAVE_GPIO_PORTO
# define GPIO_PORTO 15U
# define GPIO_PORTO_MASK (GPIO_PORTO << GPIO_PORT_OFFSET)
# define PINID_O0  (GPIO_PORTO_MASK | 0x00U)
# define PINID_O1  (GPIO_PORTO_MASK | 0x01U)
# define PINID_O2  (GPIO_PORTO_MASK | 0x02U)
# define PINID_O3  (GPIO_PORTO_MASK | 0x03U)
# define PINID_O4  (GPIO_PORTO_MASK | 0x04U)
# define PINID_O5  (GPIO_PORTO_MASK | 0x05U)
# define PINID_O6  (GPIO_PORTO_MASK | 0x06U)
# define PINID_O7  (GPIO_PORTO_MASK | 0x07U)
# define PINID_O8  (GPIO_PORTO_MASK | 0x08U)
# define PINID_O9  (GPIO_PORTO_MASK | 0x09U)
# define PINID_O10 (GPIO_PORTO_MASK | 0x0AU)
# define PINID_O11 (GPIO_PORTO_MASK | 0x0BU)
# define PINID_O12 (GPIO_PORTO_MASK | 0x0CU)
# define PINID_O13 (GPIO_PORTO_MASK | 0x0DU)
# define PINID_O14 (GPIO_PORTO_MASK | 0x0EU)
# define PINID_O15 (GPIO_PORTO_MASK | 0x0FU)
#else
# define GPIO_PORTO 0U
# define GPIO_PORTO_MASK 0U
# define PINID_O0  0U
# define PINID_O1  0U
# define PINID_O2  0U
# define PINID_O3  0U
# define PINID_O4  0U
# define PINID_O5  0U
# define PINID_O6  0U
# define PINID_O7  0U
# define PINID_O8  0U
# define PINID_O9  0U
# define PINID_O10 0U
# define PINID_O11 0U
# define PINID_O12 0U
# define PINID_O13 0U
# define PINID_O14 0U
# define PINID_O15 0U
#endif
