//
// Generated by tools/cmsis/time_find_active.sh on Sat Sep 21 07:58:56 PM EDT 2024
//

//
// This is done so that we can set SLEEP_ALARM_TIMER to 0 to auto-select
#if SLEEP_ALARM_TIMER == TIMER_NONE
# undef SLEEP_ALARM_TIMER
#endif
//
// This is done so that SLEEP_ALARM_TIMER isn't auto-selected if we don't need
// it
#if ! uHAL_USE_HIBERNATE
# undef SLEEP_ALARM_TIMER
# define SLEEP_ALARM_TIMER TIMER_NONE
#endif

//
// This is done so that we can set USCOUNTER_TIMER to 0 to auto-select
#if USCOUNTER_TIMER == TIMER_NONE
# undef USCOUNTER_TIMER
#endif
//
// This is done so that USCOUNTER_TIMER isn't auto-selected if we don't need
// it
#if ! uHAL_USE_USCOUNTER
# undef USCOUNTER_TIMER
# define USCOUNTER_TIMER TIMER_NONE
#endif

//
// Timer 6
#if defined(TIM6)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_6
# endif

# if SLEEP_ALARM_TIMER == TIMER_6
#  undef USE_TIMER6_PWM
#  define USE_TIMER6_PWM 0
#  define SLEEP_ALARM_TIM        TIM6
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM6
#  define SLEEP_ALARM_IRQn       TIM6_IRQn
#  define SLEEP_ALARM_IRQHandler TIM6_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_6
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_6
#  undef USE_TIMER6_PWM
#  define USE_TIMER6_PWM 0
#  define USCOUNTER_TIM        TIM6
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM6
#  define USCOUNTER_IRQn       TIM6_IRQn
#  define USCOUNTER_IRQHandler TIM6_IRQHandler
# endif

# ifndef USE_TIMER6_PWM
#  if defined(PINID_TIM6_CH1)
#   define USE_TIMER6_PWM 1
#  else
#   define USE_TIMER6_PWM 0
#  endif
# endif

/*
# if USE_TIMER6_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 6 PWM")
# endif
*/

#else
# undef USE_TIMER6_PWM
# define USE_TIMER6_PWM 0
#endif

//
// Timer 7
#if defined(TIM7)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_7
# endif

# if SLEEP_ALARM_TIMER == TIMER_7
#  undef USE_TIMER7_PWM
#  define USE_TIMER7_PWM 0
#  define SLEEP_ALARM_TIM        TIM7
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM7
#  define SLEEP_ALARM_IRQn       TIM7_IRQn
#  define SLEEP_ALARM_IRQHandler TIM7_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_7
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_7
#  undef USE_TIMER7_PWM
#  define USE_TIMER7_PWM 0
#  define USCOUNTER_TIM        TIM7
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM7
#  define USCOUNTER_IRQn       TIM7_IRQn
#  define USCOUNTER_IRQHandler TIM7_IRQHandler
# endif

# ifndef USE_TIMER7_PWM
#  if defined(PINID_TIM7_CH1)
#   define USE_TIMER7_PWM 1
#  else
#   define USE_TIMER7_PWM 0
#  endif
# endif

/*
# if USE_TIMER7_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 7 PWM")
# endif
*/

#else
# undef USE_TIMER7_PWM
# define USE_TIMER7_PWM 0
#endif

//
// Timer 8
#if defined(TIM8)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_8
# endif

# if SLEEP_ALARM_TIMER == TIMER_8
#  undef USE_TIMER8_PWM
#  define USE_TIMER8_PWM 0
#  define SLEEP_ALARM_TIM        TIM8
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM8
#  define SLEEP_ALARM_IRQn       TIM8_IRQn
#  define SLEEP_ALARM_IRQHandler TIM8_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_8
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_8
#  undef USE_TIMER8_PWM
#  define USE_TIMER8_PWM 0
#  define USCOUNTER_TIM        TIM8
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM8
#  define USCOUNTER_IRQn       TIM8_IRQn
#  define USCOUNTER_IRQHandler TIM8_IRQHandler
# endif

# ifndef USE_TIMER8_PWM
#  if defined(PINID_TIM8_CH1)
#   define USE_TIMER8_PWM 1
#  else
#   define USE_TIMER8_PWM 0
#  endif
# endif

/*
# if USE_TIMER8_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 8 PWM")
# endif
*/

#else
# undef USE_TIMER8_PWM
# define USE_TIMER8_PWM 0
#endif

//
// Timer 11
#if defined(TIM11)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_11
# endif

# if SLEEP_ALARM_TIMER == TIMER_11
#  undef USE_TIMER11_PWM
#  define USE_TIMER11_PWM 0
#  define SLEEP_ALARM_TIM        TIM11
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM11
#  define SLEEP_ALARM_IRQn       TIM11_IRQn
#  define SLEEP_ALARM_IRQHandler TIM11_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_11
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_11
#  undef USE_TIMER11_PWM
#  define USE_TIMER11_PWM 0
#  define USCOUNTER_TIM        TIM11
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM11
#  define USCOUNTER_IRQn       TIM11_IRQn
#  define USCOUNTER_IRQHandler TIM11_IRQHandler
# endif

# ifndef USE_TIMER11_PWM
#  if defined(PINID_TIM11_CH1)
#   define USE_TIMER11_PWM 1
#  else
#   define USE_TIMER11_PWM 0
#  endif
# endif

/*
# if USE_TIMER11_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 11 PWM")
# endif
*/

#else
# undef USE_TIMER11_PWM
# define USE_TIMER11_PWM 0
#endif

//
// Timer 13
#if defined(TIM13)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_13
# endif

# if SLEEP_ALARM_TIMER == TIMER_13
#  undef USE_TIMER13_PWM
#  define USE_TIMER13_PWM 0
#  define SLEEP_ALARM_TIM        TIM13
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM13
#  define SLEEP_ALARM_IRQn       TIM13_IRQn
#  define SLEEP_ALARM_IRQHandler TIM13_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_13
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_13
#  undef USE_TIMER13_PWM
#  define USE_TIMER13_PWM 0
#  define USCOUNTER_TIM        TIM13
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM13
#  define USCOUNTER_IRQn       TIM13_IRQn
#  define USCOUNTER_IRQHandler TIM13_IRQHandler
# endif

# ifndef USE_TIMER13_PWM
#  if defined(PINID_TIM13_CH1)
#   define USE_TIMER13_PWM 1
#  else
#   define USE_TIMER13_PWM 0
#  endif
# endif

/*
# if USE_TIMER13_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 13 PWM")
# endif
*/

#else
# undef USE_TIMER13_PWM
# define USE_TIMER13_PWM 0
#endif

//
// Timer 14
#if defined(TIM14)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_14
# endif

# if SLEEP_ALARM_TIMER == TIMER_14
#  undef USE_TIMER14_PWM
#  define USE_TIMER14_PWM 0
#  define SLEEP_ALARM_TIM        TIM14
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM14
#  define SLEEP_ALARM_IRQn       TIM14_IRQn
#  define SLEEP_ALARM_IRQHandler TIM14_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_14
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_14
#  undef USE_TIMER14_PWM
#  define USE_TIMER14_PWM 0
#  define USCOUNTER_TIM        TIM14
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM14
#  define USCOUNTER_IRQn       TIM14_IRQn
#  define USCOUNTER_IRQHandler TIM14_IRQHandler
# endif

# ifndef USE_TIMER14_PWM
#  if defined(PINID_TIM14_CH1)
#   define USE_TIMER14_PWM 1
#  else
#   define USE_TIMER14_PWM 0
#  endif
# endif

/*
# if USE_TIMER14_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 14 PWM")
# endif
*/

#else
# undef USE_TIMER14_PWM
# define USE_TIMER14_PWM 0
#endif

//
// Timer 9
#if defined(TIM9)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_9
# endif

# if SLEEP_ALARM_TIMER == TIMER_9
#  undef USE_TIMER9_PWM
#  define USE_TIMER9_PWM 0
#  define SLEEP_ALARM_TIM        TIM9
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM9
#  define SLEEP_ALARM_IRQn       TIM9_IRQn
#  define SLEEP_ALARM_IRQHandler TIM9_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_9
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_9
#  undef USE_TIMER9_PWM
#  define USE_TIMER9_PWM 0
#  define USCOUNTER_TIM        TIM9
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM9
#  define USCOUNTER_IRQn       TIM9_IRQn
#  define USCOUNTER_IRQHandler TIM9_IRQHandler
# endif

# ifndef USE_TIMER9_PWM
#  if defined(PINID_TIM9_CH1)
#   define USE_TIMER9_PWM 1
#  else
#   define USE_TIMER9_PWM 0
#  endif
# endif

/*
# if USE_TIMER9_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 9 PWM")
# endif
*/

#else
# undef USE_TIMER9_PWM
# define USE_TIMER9_PWM 0
#endif

//
// Timer 12
#if defined(TIM12)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_12
# endif

# if SLEEP_ALARM_TIMER == TIMER_12
#  undef USE_TIMER12_PWM
#  define USE_TIMER12_PWM 0
#  define SLEEP_ALARM_TIM        TIM12
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM12
#  define SLEEP_ALARM_IRQn       TIM12_IRQn
#  define SLEEP_ALARM_IRQHandler TIM12_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_12
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_12
#  undef USE_TIMER12_PWM
#  define USE_TIMER12_PWM 0
#  define USCOUNTER_TIM        TIM12
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM12
#  define USCOUNTER_IRQn       TIM12_IRQn
#  define USCOUNTER_IRQHandler TIM12_IRQHandler
# endif

# ifndef USE_TIMER12_PWM
#  if defined(PINID_TIM12_CH1)
#   define USE_TIMER12_PWM 1
#  else
#   define USE_TIMER12_PWM 0
#  endif
# endif

/*
# if USE_TIMER12_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 12 PWM")
# endif
*/

#else
# undef USE_TIMER12_PWM
# define USE_TIMER12_PWM 0
#endif

//
// Timer 10
#if defined(TIM10)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_10
# endif

# if SLEEP_ALARM_TIMER == TIMER_10
#  undef USE_TIMER10_PWM
#  define USE_TIMER10_PWM 0
#  define SLEEP_ALARM_TIM        TIM10
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM10
#  define SLEEP_ALARM_IRQn       TIM10_IRQn
#  define SLEEP_ALARM_IRQHandler TIM10_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_10
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_10
#  undef USE_TIMER10_PWM
#  define USE_TIMER10_PWM 0
#  define USCOUNTER_TIM        TIM10
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM10
#  define USCOUNTER_IRQn       TIM10_IRQn
#  define USCOUNTER_IRQHandler TIM10_IRQHandler
# endif

# ifndef USE_TIMER10_PWM
#  if defined(PINID_TIM10_CH1)
#   define USE_TIMER10_PWM 1
#  else
#   define USE_TIMER10_PWM 0
#  endif
# endif

/*
# if USE_TIMER10_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 10 PWM")
# endif
*/

#else
# undef USE_TIMER10_PWM
# define USE_TIMER10_PWM 0
#endif

//
// Timer 5
#if defined(TIM5)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_5
# endif

# if SLEEP_ALARM_TIMER == TIMER_5
#  undef USE_TIMER5_PWM
#  define USE_TIMER5_PWM 0
#  define SLEEP_ALARM_TIM        TIM5
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM5
#  define SLEEP_ALARM_IRQn       TIM5_IRQn
#  define SLEEP_ALARM_IRQHandler TIM5_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_5
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_5
#  undef USE_TIMER5_PWM
#  define USE_TIMER5_PWM 0
#  define USCOUNTER_TIM        TIM5
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM5
#  define USCOUNTER_IRQn       TIM5_IRQn
#  define USCOUNTER_IRQHandler TIM5_IRQHandler
# endif

# ifndef USE_TIMER5_PWM
#  if defined(PINID_TIM5_CH1)
#   define USE_TIMER5_PWM 1
#  else
#   define USE_TIMER5_PWM 0
#  endif
# endif

/*
# if USE_TIMER5_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 5 PWM")
# endif
*/

#else
# undef USE_TIMER5_PWM
# define USE_TIMER5_PWM 0
#endif

//
// Timer 3
#if defined(TIM3)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_3
# endif

# if SLEEP_ALARM_TIMER == TIMER_3
#  undef USE_TIMER3_PWM
#  define USE_TIMER3_PWM 0
#  define SLEEP_ALARM_TIM        TIM3
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM3
#  define SLEEP_ALARM_IRQn       TIM3_IRQn
#  define SLEEP_ALARM_IRQHandler TIM3_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_3
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_3
#  undef USE_TIMER3_PWM
#  define USE_TIMER3_PWM 0
#  define USCOUNTER_TIM        TIM3
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM3
#  define USCOUNTER_IRQn       TIM3_IRQn
#  define USCOUNTER_IRQHandler TIM3_IRQHandler
# endif

# ifndef USE_TIMER3_PWM
#  if defined(PINID_TIM3_CH1)
#   define USE_TIMER3_PWM 1
#  else
#   define USE_TIMER3_PWM 0
#  endif
# endif

/*
# if USE_TIMER3_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 3 PWM")
# endif
*/

#else
# undef USE_TIMER3_PWM
# define USE_TIMER3_PWM 0
#endif

//
// Timer 4
#if defined(TIM4)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_4
# endif

# if SLEEP_ALARM_TIMER == TIMER_4
#  undef USE_TIMER4_PWM
#  define USE_TIMER4_PWM 0
#  define SLEEP_ALARM_TIM        TIM4
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM4
#  define SLEEP_ALARM_IRQn       TIM4_IRQn
#  define SLEEP_ALARM_IRQHandler TIM4_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_4
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_4
#  undef USE_TIMER4_PWM
#  define USE_TIMER4_PWM 0
#  define USCOUNTER_TIM        TIM4
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM4
#  define USCOUNTER_IRQn       TIM4_IRQn
#  define USCOUNTER_IRQHandler TIM4_IRQHandler
# endif

# ifndef USE_TIMER4_PWM
#  if defined(PINID_TIM4_CH1)
#   define USE_TIMER4_PWM 1
#  else
#   define USE_TIMER4_PWM 0
#  endif
# endif

/*
# if USE_TIMER4_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 4 PWM")
# endif
*/

#else
# undef USE_TIMER4_PWM
# define USE_TIMER4_PWM 0
#endif

//
// Timer 2
#if defined(TIM2)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_2
# endif

# if SLEEP_ALARM_TIMER == TIMER_2
#  undef USE_TIMER2_PWM
#  define USE_TIMER2_PWM 0
#  define SLEEP_ALARM_TIM        TIM2
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM2
#  define SLEEP_ALARM_IRQn       TIM2_IRQn
#  define SLEEP_ALARM_IRQHandler TIM2_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_2
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_2
#  undef USE_TIMER2_PWM
#  define USE_TIMER2_PWM 0
#  define USCOUNTER_TIM        TIM2
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM2
#  define USCOUNTER_IRQn       TIM2_IRQn
#  define USCOUNTER_IRQHandler TIM2_IRQHandler
# endif

# ifndef USE_TIMER2_PWM
#  if defined(PINID_TIM2_CH1)
#   define USE_TIMER2_PWM 1
#  else
#   define USE_TIMER2_PWM 0
#  endif
# endif

/*
# if USE_TIMER2_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 2 PWM")
# endif
*/

#else
# undef USE_TIMER2_PWM
# define USE_TIMER2_PWM 0
#endif

//
// Timer 1
#if defined(TIM1)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_1
# endif

# if SLEEP_ALARM_TIMER == TIMER_1
#  undef USE_TIMER1_PWM
#  define USE_TIMER1_PWM 0
#  define SLEEP_ALARM_TIM        TIM1
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIM1
#  define SLEEP_ALARM_IRQn       TIM1_IRQn
#  define SLEEP_ALARM_IRQHandler TIM1_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_1
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_1
#  undef USE_TIMER1_PWM
#  define USE_TIMER1_PWM 0
#  define USCOUNTER_TIM        TIM1
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIM1
#  define USCOUNTER_IRQn       TIM1_IRQn
#  define USCOUNTER_IRQHandler TIM1_IRQHandler
# endif

# ifndef USE_TIMER1_PWM
#  if defined(PINID_TIM1_CH1)
#   define USE_TIMER1_PWM 1
#  else
#   define USE_TIMER1_PWM 0
#  endif
# endif

/*
# if USE_TIMER1_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG("Using timer 1 PWM")
# endif
*/

#else
# undef USE_TIMER1_PWM
# define USE_TIMER1_PWM 0
#endif

#ifndef DISABLE_PORTA_PWM
# define DISABLE_PORTA_PWM 0
#endif
#define HAVE_GPIO_PORTA_PWM (HAVE_GPIO_PORTA && ! DISABLE_PORTA_PWM)

#ifndef DISABLE_PORTB_PWM
# define DISABLE_PORTB_PWM 0
#endif
#define HAVE_GPIO_PORTB_PWM (HAVE_GPIO_PORTB && ! DISABLE_PORTB_PWM)

#ifndef DISABLE_PORTC_PWM
# define DISABLE_PORTC_PWM 0
#endif
#define HAVE_GPIO_PORTC_PWM (HAVE_GPIO_PORTC && ! DISABLE_PORTC_PWM)

#ifndef DISABLE_PORTD_PWM
# define DISABLE_PORTD_PWM 0
#endif
#define HAVE_GPIO_PORTD_PWM (HAVE_GPIO_PORTD && ! DISABLE_PORTD_PWM)

#ifndef DISABLE_PORTE_PWM
# define DISABLE_PORTE_PWM 0
#endif
#define HAVE_GPIO_PORTE_PWM (HAVE_GPIO_PORTE && ! DISABLE_PORTE_PWM)

#ifndef DISABLE_PORTF_PWM
# define DISABLE_PORTF_PWM 0
#endif
#define HAVE_GPIO_PORTF_PWM (HAVE_GPIO_PORTF && ! DISABLE_PORTF_PWM)

#ifndef DISABLE_PORTG_PWM
# define DISABLE_PORTG_PWM 0
#endif
#define HAVE_GPIO_PORTG_PWM (HAVE_GPIO_PORTG && ! DISABLE_PORTG_PWM)

#ifndef DISABLE_PORTH_PWM
# define DISABLE_PORTH_PWM 0
#endif
#define HAVE_GPIO_PORTH_PWM (HAVE_GPIO_PORTH && ! DISABLE_PORTH_PWM)

#ifndef DISABLE_PORTI_PWM
# define DISABLE_PORTI_PWM 0
#endif
#define HAVE_GPIO_PORTI_PWM (HAVE_GPIO_PORTI && ! DISABLE_PORTI_PWM)

#ifndef DISABLE_PORTJ_PWM
# define DISABLE_PORTJ_PWM 0
#endif
#define HAVE_GPIO_PORTJ_PWM (HAVE_GPIO_PORTJ && ! DISABLE_PORTJ_PWM)

#ifndef DISABLE_PORTK_PWM
# define DISABLE_PORTK_PWM 0
#endif
#define HAVE_GPIO_PORTK_PWM (HAVE_GPIO_PORTK && ! DISABLE_PORTK_PWM)

#ifndef DISABLE_PORTL_PWM
# define DISABLE_PORTL_PWM 0
#endif
#define HAVE_GPIO_PORTL_PWM (HAVE_GPIO_PORTL && ! DISABLE_PORTL_PWM)

#ifndef DISABLE_PORTM_PWM
# define DISABLE_PORTM_PWM 0
#endif
#define HAVE_GPIO_PORTM_PWM (HAVE_GPIO_PORTM && ! DISABLE_PORTM_PWM)

#ifndef DISABLE_PORTN_PWM
# define DISABLE_PORTN_PWM 0
#endif
#define HAVE_GPIO_PORTN_PWM (HAVE_GPIO_PORTN && ! DISABLE_PORTN_PWM)

#ifndef DISABLE_PORTO_PWM
# define DISABLE_PORTO_PWM 0
#endif
#define HAVE_GPIO_PORTO_PWM (HAVE_GPIO_PORTO && ! DISABLE_PORTO_PWM)
