#include "../../lib/uHAL/config/config_AVR_XMEGA3.h"

// ATTiny402 SOIC-8 pinout
#define PIN_2 PINID_A6 // button, TCB0 PWM
#define PIN_3 PINID_A7 // ADC test
#define PIN_4 PINID_A1 // SDA, remapped UART TX, TCA0 PWM
#define PIN_5 PINID_A2 // SCL, remapped UART RX, TCA0 PWM
#define PIN_6 PINID_A0 // RESET and UPDI
#define PIN_7 PINID_A3 // LED, TCA0 PWM

// Use A1/A2 instead of A6/A7
#undef  GPIO_REMAP_UART0
#define GPIO_REMAP_UART0 1

//#define LED_PIN  (PIN_7 | GPIO_CTRL_TRISTATE_HIGH | GPIO_CTRL_INVERT)
//#define LED_PIN  (PIN_7 | GPIO_CTRL_TRISTATE_LOW)
#define LED_PIN  (PIN_7 | GPIO_CTRL_PUSHPULL)
#define LED_PINCTRL_PIN  LED_PIN
#define LED_PINCTRL2_PIN LED_PIN

#define PWM_LED_PIN  LED_PIN

//#undef  ADC_MAX
//#define ADC_MAX 0x0FF
#define ADC_TEST_PIN PIN_3
#define ADC_TEST_PIN_GND 0
#define ADC_TEST_PIN_VCC 0

#define BUTTON_PIN_UNBIASED PINID_A6
#define BUTTON_PIN (BUTTON_PIN_UNBIASED | GPIO_CTRL_PULLUP | GPIO_CTRL_INVERT)

//#undef SYSTICK_TIMER
//#define SYSTICK_TIMER TIMER_RTT

//#undef USCOUNTER_TIMER
//#define USCOUNTER_TIMER TIMER_TCB0

#undef  RTT_RECALIBRATE_INTERVAL_S
#define RTT_RECALIBRATE_INTERVAL_S 0

#define F_OSC  16000000UL
#undef  F_CORE
#define F_CORE 4000000UL

/*
#undef SYSTICK_TIMER
#define SYSTICK_TIMER TIMER_TCB0

#undef USCOUNTER_TIMER
#define USCOUNTER_TIMER TIMER_TCA0
*/
