// ATTiny402 SOIC-8 pinout
#define PIN_2 PINID_A6 // button, TCB0 PWM
#define PIN_3 PINID_A7 // ADC test
#define PIN_4 PINID_A1 // SDA, remapped UART TX, TCA0 PWM
#define PIN_5 PINID_A2 // SCL, remapped UART RX, TCA0 PWM
#define PIN_6 PINID_A0 // RESET and UPDI
#define PIN_7 PINID_A3 // LED, TCA0 PWM

#define GPIO_REMAP_I2C0   0
#define GPIO_REMAP_SPI0   0
#define GPIO_REMAP_UART0  1 // Use A1/A2 instead of A6/A7 for UART
#define GPIO_REMAP_TCA0W0 0
#define GPIO_REMAP_TCA0W1 0
#define GPIO_REMAP_TCA0W2 0
#define GPIO_REMAP_TCA0W3 0
#define GPIO_REMAP_TCB0   0
//
// UART serial console pins
#define UART_COMM_TX_PIN PINID_UART0_TX
#define UART_COMM_RX_PIN PINID_UART0_RX
//
// SPI pins
#define SPI_SS_PIN    PINID_SPI0_SS
#define SPI_SCK_PIN   PINID_SPI0_SCK
#define SPI_MISO_PIN  PINID_SPI0_MISO
#define SPI_MOSI_PIN  PINID_SPI0_MOSI
#define SPI_CS_SD_PIN SPI_SS_PIN
//
// I2C pins
#define I2C_SDA_PIN PINID_I2C0_SDA
#define I2C_SCL_PIN PINID_I2C0_SCL

//#define LED_PIN  (PIN_7 | GPIO_CTRL_TRISTATE_HIGH | GPIO_CTRL_INVERT)
//#define LED_PIN  (PIN_7 | GPIO_CTRL_TRISTATE_LOW)
#define LED_PIN  (PIN_7 | GPIO_CTRL_PUSHPULL)
#define LED_PINCTRL_PIN  LED_PIN
#define LED_PINCTRL2_PIN LED_PIN

#define PWM_LED_PIN  LED_PIN

//#define ADC_MAX 0x0FF
#define ADC_TEST_PIN PIN_3
#define ADC_TEST_PIN_GND 0
#define ADC_TEST_PIN_VCC 0

#define BUTTON_PIN_UNBIASED PINID_A6
#define BUTTON_PIN (BUTTON_PIN_UNBIASED | GPIO_CTRL_PULLUP | GPIO_CTRL_INVERT)

//#define SYSTICK_TIMER TIMER_RTT

//#define USCOUNTER_TIMER TIMER_TCB0

#define RTT_RECALIBRATE_INTERVAL_S 0

#define F_OSC  16000000UL
#define F_CORE 4000000UL

/*
#define SYSTICK_TIMER TIMER_TCB0

#define USCOUNTER_TIMER TIMER_TCA0
*/
