#undef UART_COMM_TX_PIN
#undef UART_COMM_RX_PIN
#define UART_COMM_TX_PIN PINID_B6 // B6, A9
#define UART_COMM_RX_PIN PINID_B7 // B7, A10

#undef I2C_SDA_PIN
#undef I2C_SCL_PIN
#define I2C_SDA_PIN PINID_B9 // B9, B7
#define I2C_SCL_PIN PINID_B8 // B8, B6

#define LED_PIN (PINID_A12)
#define LED_PINCTRL_PIN  (PINID_A11 | GPIO_CTRL_OPENDRAIN)
//#define LED_PINCTRL_PIN  (PINID_A11 | GPIO_CTRL_OPENDRAIN | GPIO_CTRL_INVERT)
//#define LED_PINCTRL_PIN  (PINID_A0 | GPIO_CTRL_PUSHPULL)
#define LED_PINCTRL2_PIN LED_PINCTRL_PIN

#define PWM_LED_PIN PINID_A8
//#define PWM_LED_PIN PINID_A3

//# undef ADC_MAX
//#define ADC_MAX 0x00FF
#define ADC_TEST_PIN PINID_A0 // Vcc -> 22K -> 8.1K -> Gnd
#define ADC_TEST_PIN_GND PINID_A1
#define ADC_TEST_PIN_VCC PINID_A2

#define BUTTON_PIN_UNBIASED PINID_A3
#define BUTTON_PIN (BUTTON_PIN_UNBIASED | GPIO_CTRL_PULLUP | GPIO_CTRL_INVERT)

#undef uHAL_BACKUP_DOMAIN_RESET
#define uHAL_BACKUP_DOMAIN_RESET 0

#undef uHAL_USE_INTERNAL_OSC
#undef uHAL_USE_INTERNAL_LS_OSC
#undef F_CORE
#undef F_HCLK
#undef F_PCLK1
#undef F_PCLK2

#define F_OSC  25000000UL
#define F_CORE 48000000UL
#define uHAL_USE_INTERNAL_OSC 0
#define uHAL_USE_INTERNAL_LS_OSC 0

#define F_HCLK  48000000UL
//#define F_PCLK1 (F_HCLK/2U)
//#define F_PCLK2 (F_HCLK)

//#undef SLEEP_ALARM_TIMER
//#define SLEEP_ALARM_TIMER 3
