//
// ulibconfig.h
// Configuration file for the ulib modules
//
// Descriptions of the settings used can be found in the ulib default configuration
// file.
//

#define DEBUG_CPP_MESSAGES 0

#define ULIB_ENABLE_DEFAULT 0
#define ULIB_USE_STRUCT_ID  0
#define ULIB_USE_MALLOC     0

#define ULIB_DO_SAFETY_CHECKS 0

#define ULIB_ENABLE_FMEM 1
#define FMEM_STR_BYTES 96U

#define ULIB_ENABLE_ASCII 1
#define ASCII_SUBSTITUTE_WITH_CTYPE 0
#define ASCII_SUBSTITUTE_FOR_CTYPE 0

#define ULIB_ENABLE_BITOPS 1
#define ULIB_BITOP_ENABLE_INLINED_FUNCTIONS 1
#define ULIB_BITOP_ENABLE_INLINED_64BIT_FUNCTIONS 1
#define ULIB_BITOP_ENABLE_GENERICS 1

#define ULIB_ENABLE_CSTRINGS 1

#define USE_ULIB_ASSERT 1
#define USE_ULIB_LOCAL_ASSERT 1
#define USE_ULIB_ASSERT_OVERRIDE 1
#define USE_ULIB_PANIC 0
#define USE_ULIB_LOCAL_PANIC 0
//#define DEBUG_CPP_MESSAGES DEBUG

#define ULIB_ENABLE_ERROR 1
#define ULIB_ENABLE_ERROR_TRANSLATION 0

#define ULIB_ENABLE_MATH 1

#define ULIB_ENABLE_FIXED_POINT 1
#define FIXED_POINT_BITS 32
#define FIXED_POINT_FRACT_BITS 8
//#define FIXED_POINT_REPLACE_WITH_FLOAT 0

#define ULIB_ENABLE_PRINTF 1
#define PRINTF_MAX_INT_BYTES 4
#define PRINTF_USE_MINIMAL_FEATURE_SET 1
#define PRINTF_TRY_LARGE_INTS 0
#define PRINTF_ALLOW_BINARY 1
#define PRINTF_ALLOW_UNCOMMON_INTS 1
#define PRINTF_ALLOW_ALT_FORMS 1
#define PRINTF_ALLOW_ZERO_PADDING 1
#define PRINTF_ALLOW_PRECISION 1

#define ULIB_ENABLE_TIME 1
#define TIME_YEAR_0 2015U

#define ULIB_ENABLE_UTIL 1

#include "../../lib/ulib/ulibconfig_template.h"
