#!/bin/sh

I2Cs="1 2 3"

template="
//
// I2Cnnn
//
#if defined(I2Cnnn)
# define HAVE_I2Cnnn 1
#else
# define HAVE_I2Cnnn 0
#endif

#if HAVE_I2Cnnn
# if defined(PINID_I2Cnnn_SDA) && PINID_I2Cnnn_SDA > 0
#  define IS_I2Cnnn_SDA_DEF(_p_) (PINID(_p_) == PINID_I2Cnnn_SDA)
# else
#  define IS_I2Cnnn_SDA_DEF(_p_) (0)
# endif
# if defined(PINID_I2Cnnn_SDA_ALT2) && PINID_I2Cnnn_SDA_ALT2 > 0
#  define IS_I2Cnnn_SDA_ALT2(_p_) (PINID(_p_) == PINID_I2Cnnn_SDA_ALT2)
# else
#  define IS_I2Cnnn_SDA_ALT2(_p_) (0)
# endif
# if defined(PINID_I2Cnnn_SDA_ALT) && PINID_I2Cnnn_SDA_ALT > 0
#  define IS_I2Cnnn_SDA_ALT1(_p_) (PINID(_p_) == PINID_I2Cnnn_SDA_ALT)
# else
#  define IS_I2Cnnn_SDA_ALT1(_p_) (0)
# endif
# define IS_I2Cnnn_SDA(_p_) (IS_I2Cnnn_SDA_DEF(_p_) || IS_I2Cnnn_SDA_ALT1(_p_) || IS_I2Cnnn_SDA_ALT2(_p_))

# if defined(PINID_I2Cnnn_SCL) && PINID_I2Cnnn_SCL > 0
#  define IS_I2Cnnn_SCL_DEF(_p_) (PINID(_p_) == PINID_I2Cnnn_SCL)
# else
#  define IS_I2Cnnn_SCL_DEF(_p_) (0)
# endif
# if defined(PINID_I2Cnnn_SCL_ALT2) && PINID_I2Cnnn_SCL_ALT2 > 0
#  define IS_I2Cnnn_SCL_ALT2(_p_) (PINID(_p_) == PINID_I2Cnnn_SCL_ALT2)
# else
#  define IS_I2Cnnn_SCL_ALT2(_p_) (0)
# endif
# if defined(PINID_I2Cnnn_SCL_ALT) && PINID_I2Cnnn_SCL_ALT > 0
#  define IS_I2Cnnn_SCL_ALT1(_p_) (PINID(_p_) == PINID_I2Cnnn_SCL_ALT)
# else
#  define IS_I2Cnnn_SCL_ALT1(_p_) (0)
# endif
# define IS_I2Cnnn_SCL(_p_) (IS_I2Cnnn_SCL_DEF(_p_) || IS_I2Cnnn_SCL_ALT1(_p_) || IS_I2Cnnn_SCL_ALT2(_p_))

# define IS_I2Cnnn(_sdap_, _sclp_) (IS_I2Cnnn_SDA(_sdap_) && IS_I2Cnnn_SCL(_sclp_))

# if IS_I2Cnnn(I2C_SDA_PIN, I2C_SCL_PIN)
#  define I2Cx I2Cnnn
#  define I2Cx_CLOCKEN RCC_PERIPH_I2Cnnn
#  define I2Cx_AF GPIOAF_I2Cnnn
# endif

#else // HAVE_I2Cnnn
# define IS_I2Cnnn(_sdap_, _sclp_) (0)
#endif // HAVE_I2Cnnn
"

cat << EOF
//
// Generated by ${0} on $(date)
//

#if INCLUDED_BY_I2C_C

EOF

for n in ${I2Cs}; do
	printf "%s" "${template}" | sed -e "s|nnn|${n}|g"
done

cat << EOF

#endif // INCLUDED_BY_I2C_C
EOF
