#!/bin/sh

# 15 ports is 4 bits with 0 reserved
ports="${PORTS:-A B C D E F G H I J K L M N O}"

template="
//
// Port NNN
#ifndef HAVE_GPIO_PORTNNN
# if HAVE_GPIO_PORT_DEFAULT && defined(GPIONNN)
#  define HAVE_GPIO_PORTNNN 1
# else
#  define HAVE_GPIO_PORTNNN 0
# endif
#endif
#if HAVE_GPIO_PORTNNN
# define GPIO_PORTNNN ZZZU
# define GPIO_PORTNNN_MASK (GPIO_PORTNNN << GPIO_PORT_OFFSET)
# define PINID_NNN0  (GPIO_PORTNNN_MASK | 0x00U)
# define PINID_NNN1  (GPIO_PORTNNN_MASK | 0x01U)
# define PINID_NNN2  (GPIO_PORTNNN_MASK | 0x02U)
# define PINID_NNN3  (GPIO_PORTNNN_MASK | 0x03U)
# define PINID_NNN4  (GPIO_PORTNNN_MASK | 0x04U)
# define PINID_NNN5  (GPIO_PORTNNN_MASK | 0x05U)
# define PINID_NNN6  (GPIO_PORTNNN_MASK | 0x06U)
# define PINID_NNN7  (GPIO_PORTNNN_MASK | 0x07U)
# define PINID_NNN8  (GPIO_PORTNNN_MASK | 0x08U)
# define PINID_NNN9  (GPIO_PORTNNN_MASK | 0x09U)
# define PINID_NNN10 (GPIO_PORTNNN_MASK | 0x0AU)
# define PINID_NNN11 (GPIO_PORTNNN_MASK | 0x0BU)
# define PINID_NNN12 (GPIO_PORTNNN_MASK | 0x0CU)
# define PINID_NNN13 (GPIO_PORTNNN_MASK | 0x0DU)
# define PINID_NNN14 (GPIO_PORTNNN_MASK | 0x0EU)
# define PINID_NNN15 (GPIO_PORTNNN_MASK | 0x0FU)
#else
# define GPIO_PORTNNN 0U
# define GPIO_PORTNNN_MASK 0U
# define PINID_NNN0  0U
# define PINID_NNN1  0U
# define PINID_NNN2  0U
# define PINID_NNN3  0U
# define PINID_NNN4  0U
# define PINID_NNN5  0U
# define PINID_NNN6  0U
# define PINID_NNN7  0U
# define PINID_NNN8  0U
# define PINID_NNN9  0U
# define PINID_NNN10 0U
# define PINID_NNN11 0U
# define PINID_NNN12 0U
# define PINID_NNN13 0U
# define PINID_NNN14 0U
# define PINID_NNN15 0U
#endif
"
cat <<- EOF
//
// Generated by ${0##*/} on $(date)
//

#ifndef HAVE_GPIO_PORT_DEFAULT
# define HAVE_GPIO_PORT_DEFAULT 0
#endif
EOF

i=1
for p in ${ports}; do
	printf "%s" "${template}" | sed -e "s|NNN|${p}|g" -e "s|ZZZ|${i}|g"
	i=$((i+1))
done
