#!/bin/sh

SPIs="1 2 3 4 5 6"

template="
//
// SPInnn
//
#if defined(SPInnn)
# define HAVE_SPInnn 1
#else
# define HAVE_SPInnn 0
#endif

#if HAVE_SPInnn
# if defined(PINID_SPInnn_MOSI) && PINID_SPInnn_MOSI > 0
#  define IS_SPInnn_MOSI_DEF(_p_) (PINID(_p_) == PINID_SPInnn_MOSI)
# else
#  define IS_SPInnn_MOSI_DEF(_p_) (0)
# endif
# if defined(PINID_SPInnn_MOSI_ALT2) && PINID_SPInnn_MOSI_ALT2 > 0
#  define IS_SPInnn_MOSI_ALT2(_p_) (PINID(_p_) == PINID_SPInnn_MOSI_ALT2)
# else
#  define IS_SPInnn_MOSI_ALT2(_p_) (0)
# endif
# if defined(PINID_SPInnn_MOSI_ALT) && PINID_SPInnn_MOSI_ALT > 0
#  define IS_SPInnn_MOSI_ALT1(_p_) (PINID(_p_) == PINID_SPInnn_MOSI_ALT)
# else
#  define IS_SPInnn_MOSI_ALT1(_p_) (0)
# endif
# define IS_SPInnn_MOSI(_p_) (IS_SPInnn_MOSI_DEF(_p_) || IS_SPInnn_MOSI_ALT1(_p_) || IS_SPInnn_MOSI_ALT2(_p_))

# if defined(PINID_SPInnn_MISO) && PINID_SPInnn_MISO > 0
#  define IS_SPInnn_MISO_DEF(_p_) (PINID(_p_) == PINID_SPInnn_MISO)
# else
#  define IS_SPInnn_MISO_DEF(_p_) (0)
# endif
# if defined(PINID_SPInnn_MISO_ALT2) && PINID_SPInnn_MISO_ALT2 > 0
#  define IS_SPInnn_MISO_ALT2(_p_) (PINID(_p_) == PINID_SPInnn_MISO_ALT2)
# else
#  define IS_SPInnn_MISO_ALT2(_p_) (0)
# endif
# if defined(PINID_SPInnn_MISO_ALT) && PINID_SPInnn_MISO_ALT > 0
#  define IS_SPInnn_MISO_ALT1(_p_) (PINID(_p_) == PINID_SPInnn_MISO_ALT)
# else
#  define IS_SPInnn_MISO_ALT1(_p_) (0)
# endif
# define IS_SPInnn_MISO(_p_) (IS_SPInnn_MISO_DEF(_p_) || IS_SPInnn_MISO_ALT1(_p_) || IS_SPInnn_MISO_ALT2(_p_))

# if defined(PINID_SPInnn_SCK) && PINID_SPInnn_SCK > 0
#  define IS_SPInnn_SCK_DEF(_p_) (PINID(_p_) == PINID_SPInnn_SCK)
# else
#  define IS_SPInnn_SCK_DEF(_p_) (0)
# endif
# if defined(PINID_SPInnn_SCK_ALT2) && PINID_SPInnn_SCK_ALT2 > 0
#  define IS_SPInnn_SCK_ALT2(_p_) (PINID(_p_) == PINID_SPInnn_SCK_ALT2)
# else
#  define IS_SPInnn_SCK_ALT2(_p_) (0)
# endif
# if defined(PINID_SPInnn_SCK_ALT) && PINID_SPInnn_SCK_ALT > 0
#  define IS_SPInnn_SCK_ALT1(_p_) (PINID(_p_) == PINID_SPInnn_SCK_ALT)
# else
#  define IS_SPInnn_SCK_ALT1(_p_) (0)
# endif
# define IS_SPInnn_SCK(_p_) (IS_SPInnn_SCK_DEF(_p_) || IS_SPInnn_SCK_ALT1(_p_) || IS_SPInnn_SCK_ALT2(_p_))

# define IS_SPInnn(_mosi_, _miso_, _sck_) (IS_SPInnn_MOSI(_mosi_) && IS_SPInnn_MISO(_miso_) && IS_SPInnn_SCK(_sck_))

# if IS_SPInnn(SPI_MOSI_PIN, SPI_MISO_PIN, SPI_SCK_PIN)
#  define SPIx SPInnn
#  define SPIx_CLOCKEN RCC_PERIPH_SPInnn
#  define SPIx_AF GPIOAF_SPInnn
# endif

#else // HAVE_SPInnn
# define IS_SPInnn(_mosi_, _miso_, _sck_) (0)
#endif // HAVE_SPInnn
"

cat << EOF
//
// Generated by ${0} on $(date)
//

#if INCLUDED_BY_SPI_C

EOF

for n in ${SPIs}; do
	printf "%s" "${template}" | sed -e "s|nnn|${n}|g"
done

cat << EOF

#endif // INCLUDED_BY_SPI_C
EOF
