#!/bin/sh
# A tool for generating the PLL clock-determination header for non-F1 line
# STM32s
#
# These devices have three relevent prescalers:
#    PLLM is used to divide the source so that it's 1-2MHz when fed to VCO
#    PLLN is used to multiply the VCO input so that it's 192-432MHz,
#    100-432MHz, or 50-432MHz (depending on the device) when fed to the PLL
#    PLLP is used to divide the PLL output
#

# These should be the min/max values for all supported architectures, they'll
# be further refined by the caller
PLLM_MIN="${PLLM_MIN:-2}"
PLLM_MAX="${PLLM_MAX:-63}"
PLLN_MIN="${PLLN_MIN:-1}"
PLLN_MAX="${PLLN_MAX:-511}"

# List of possible PLL output prescalers
PLLP_PSC="${PLLP_PSC:-2 4 6 8}"

show_help() {
	echo "Usage: ${0} <header>" >&2
	echo "Files <header>.h, <header>_1.h, and <header>_2.h will be created"
	echo "The files must not already exist." >&2
}

if [ -z "${1}" ] || [ "${1}" = "--help" ] || [ "${1}" = "-h" ]; then
	show_help
	exit 0
fi
LOOP_1="${1}.h"
LOOP_2="${1}_1.h"
LOOP_3="${1}_2.h"
if [ -e "${LOOP_1}" ] || [ -e "${LOOP_2}" ] || [ -e "${LOOP_3}" ]; then
	show_help
	exit 1
fi


cat >>"${LOOP_1}" <<-EOF
/*
* This file was generated by ${0} on $(date)
*
* Attempt to generate PLL prescaler values for STM32Fx devices (excluding the F1s)
* The output clock is ((oscillator_freq / PLLM) * PLLN) / PLLP
*
* Supports PLLN ranging from ${PLLN_MIN}-${PLLN_MAX} and PLLM from ${PLLM_MIN}-${PLLM_MAX}
*
* FREQ_INPUT_HZ must be set to the frequency of the source oscillator
* FREQ_OUTPUT_HZ must be set to the desired frequency of the system clock
*
* VCO_INPUT_{MIN,MAX}_HZ must be set to the minimum/maximum speeds of the VCO input
* VCO_OUTPUT_{MIN,MAX}_HZ must be set to the minimum/maximum speeds of the VCO output
* PLLM_{MIN,MAX} must be set to the minimum/maximum values of the PLLM prescaler
* PLLN_{MIN,MAX} must be set to the minimum/maximum values of the PLLN prescaler
* The above values can be found in the reference manual
*
* If successful:
*    PLLM is set to the value of the PLLM prescaler
*    PLLN is set to the value of the PLLN prescaler
*    PLLP is set to PLLP_DIV_{${PLLP_PSC}}, which are caller-defined
*    PLLP_DIV is set to {${PLLP_PSC}}
*    PLL_OUTPUT_HZ is set to the PLL output frequency
*    VCO_{INPUT,OUTPUT}_HZ are set to the VCO input/output frequencies
*
* If unsuccessful, PLLP is not set.
*/
#if !defined(FREQ_INPUT_HZ)
# error "FREQ_INPUT_HZ must be defined"
#endif
#if ! defined(FREQ_OUTPUT_HZ)
# error "FREQ_OUTPUT_HZ must be defined"
#endif
#if ! defined(VCO_INPUT_MAX_HZ)
# error "VCO_INPUT_MAX_HZ must be defined"
#endif
#if ! defined(VCO_INPUT_MIN_HZ)
# error "VCO_INPUT_MIN_HZ must be defined"
#endif
#if ! defined(VCO_OUTPUT_MAX_HZ)
# error "VCO_OUTPUT_MAX_HZ must be defined"
#endif
#if ! defined(VCO_OUTPUT_MIN_HZ)
# error "VCO_OUTPUT_MIN_HZ must be defined"
#endif
#if ! defined(PLLM_MIN)
# error "PLLM_MIN must be defined"
#endif
#if ! defined(PLLM_MAX)
# error "PLLM_MAX must be defined"
#endif
#if ! defined(PLLN_MIN)
# error "PLLN_MIN must be defined"
#endif
#if ! defined(PLLN_MAX)
# error "PLLN_MAX must be defined"
#endif


#define PLLP_IGNORE 0xFF

#undef PLLP_DIV
#undef PLL_OUTPUT_HZ
#undef VCO_OUTPUT_HZ
#undef VCO_INPUT_HZ

// Per the reference manual VCO input should be close to 2 to minimize
// jitter so start high and work down
#undef PLLM
#define PLLM (FREQ_INPUT_HZ / VCO_INPUT_MAX_HZ)
#if PLLM < PLLM_MIN
# undef PLLM
# define PLLM PLLM_MIN
#endif

EOF
for m in $(seq ${PLLM_MIN} ${PLLM_MAX}); do
	cat <<-EOF
	#if (PLLM == ${m}) && (!defined(PLLP_DIV)) && (PLLM <= PLLM_MAX)
	# undef  VCO_INPUT_HZ
	# define VCO_INPUT_HZ (FREQ_INPUT_HZ / PLLM)
	# if VCO_INPUT_HZ >= VCO_INPUT_MIN_HZ
	#  include "${LOOP_2##*/}"
	#  if ! defined(PLLP_DIV)
	#   undef  PLLM
	#   define PLLM ($((m+1))U) // Failed, try next
	#  endif
	# else
	#  define PLLP_DIV PLLP_IGNORE // Ignore the rest, can't hit our goal
	# endif
	#endif // PLLM == ${m}

	EOF
done >>"${LOOP_1}"
cat >>"${LOOP_1}" <<-EOF
#if PLLP_DIV == PLLP_IGNORE
# undef PLLP_DIV
#endif
#if defined(PLLP_DIV)
# if PLLP_DIV == 2
#  define PLLP PLLP_DIV_2
# elif PLLP_DIV == 4
#  define PLLP PLLP_DIV_4
# elif PLLP_DIV == 6
#  define PLLP PLLP_DIV_6
# elif PLLP_DIV == 8
#  define PLLP PLLP_DIV_8
# else
#  error "Unhandled PLLP value"
# endif
#endif

#undef PLLP_IGNORE
// Might as well keep this if we're keeping the rest
//#undef PLLP_DIV
// This is useful for setting the oscillator frequency
//#undef PLL_OUTPUT_HZ
// These are used in the definitions of the register values so keep them
//#undef VCO_OUTPUT_HZ
//#undef VCO_INPUT_HZ
EOF

cat >>"${LOOP_2}" <<-EOF
/*
* This file was generated by ${0} on $(date)
*
* Here we search for a value of PLLN which produces a valid frequency for
* the VCO output (VCO_OUTPUT_HZ) given a specified VCO input frequency
* (VCO_INPUT_HZ)
*
* VCO_INPUT_HZ was defined in ${LOOP_1}
*/

#undef PLLN
#define PLLN (VCO_OUTPUT_MIN_HZ / VCO_INPUT_HZ)
#if PLLN < PLLN_MIN
# undef  PLLN
# define PLLN PLLN_MIN
#endif

EOF
for n in $(seq ${PLLN_MIN} ${PLLN_MAX}); do
	cat <<-EOF
	#if (PLLN == ${n}) && (PLLN <= PLLN_MAX)
	# undef  VCO_OUTPUT_HZ
	# define VCO_OUTPUT_HZ (VCO_INPUT_HZ * PLLN)
	# if VCO_OUTPUT_HZ <= VCO_OUTPUT_MAX_HZ
	#  include "${LOOP_3##*/}"
	#  if ! defined(PLLP_DIV)
	#   undef  PLLN
	#   define PLLN ($((n+1))U) // Failed, try next
	#  endif
	# else
	#  undef  PLLN
	#  define PLLN ($((PLLN_MAX+1))U) // Ignore the rest, try next PLLM value
	# endif
	#endif // PLLN == ${n}

	EOF
done >>"${LOOP_2}"

cat >>"${LOOP_3}" <<-EOF
/*
* This file was generated by ${0} on $(date)
*
* Here we search for a PLLP division ratio which produces a valid frequency
* for the PLL output (PLL_OUTPUT_HZ) given a specified VCO output frequency
* (VCO_OUTPUT_HZ)
*
* VCO_OUTPUT_HZ was defined in ${LOOP_2}
*/

EOF
for p in ${PLLP_PSC}; do
	cat <<-EOF
	#if !defined(PLLP_DIV)
	# undef PLL_OUTPUT_HZ
	# define PLL_OUTPUT_HZ (VCO_OUTPUT_HZ / ${p}U)
	# if (PLL_OUTPUT_HZ == FREQ_OUTPUT_HZ) && (PLL_OUTPUT_HZ >= PLL_OUTPUT_MIN_HZ)
	#  define PLLP_DIV ${p}U
	# endif
	#endif

	EOF
done >>"${LOOP_3}"
