#!/bin/sh

timers_4ch="1 2 3 4 5 8"
timers_2ch="9 12"
timers_1ch="10 11 13 14"
timers="${timers_4ch} ${timers_2ch} ${timers_1ch}"


template_4ch="
	//
	// Timer NNN
#if USE_TIMERNNN_PWM
	switch (PINID(pin)) {
	case PINID_TIMNNN_CH1:
# if defined(PINID_TIMNNN_CH1_ALT) && PINID_TIMNNN_CH1_ALT > 0
	case PINID_TIMNNN_CH1_ALT:
# endif
# if defined(PINID_TIMNNN_CH1_ALT2) && PINID_TIMNNN_CH1_ALT2 > 0
	case PINID_TIMNNN_CH1_ALT2:
# endif
		--ch;
# if defined(PINID_TIMNNN_CH2) && PINID_TIMNNN_CH2 > 0
	// fall through
	case PINID_TIMNNN_CH2:
# endif
# if defined(PINID_TIMNNN_CH2_ALT) && PINID_TIMNNN_CH2_ALT > 0
	case PINID_TIMNNN_CH2_ALT:
# endif
# if defined(PINID_TIMNNN_CH2_ALT2) && PINID_TIMNNN_CH2_ALT2 > 0
	case PINID_TIMNNN_CH2_ALT2:
# endif
		--ch;
# if defined(PINID_TIMNNN_CH3) && PINID_TIMNNN_CH3 > 0
	// fall through
	case PINID_TIMNNN_CH3:
# endif
# if defined(PINID_TIMNNN_CH3_ALT) && PINID_TIMNNN_CH3_ALT > 0
	case PINID_TIMNNN_CH3_ALT:
# endif
# if defined(PINID_TIMNNN_CH3_ALT2) && PINID_TIMNNN_CH3_ALT2 > 0
	case PINID_TIMNNN_CH3_ALT2:
# endif
		--ch;
# if defined(PINID_TIMNNN_CH4) && PINID_TIMNNN_CH4 > 0
	// fall through
	case PINID_TIMNNN_CH4:
# endif
# if defined(PINID_TIMNNN_CH4_ALT) && PINID_TIMNNN_CH4_ALT > 0
	case PINID_TIMNNN_CH4_ALT:
# endif
# if defined(PINID_TIMNNN_CH4_ALT2) && PINID_TIMNNN_CH4_ALT2 > 0
	case PINID_TIMNNN_CH4_ALT2:
# endif
		TIMx = TIMNNN;
		TIMxEN = RCC_PERIPH_TIMNNN;
		af = GPIOAF_TIMNNN;
		goto END;
	}
#endif // USE_TIMERNNN_PWM
"

cat << EOF
//
// Generated by ${0} on $(date)
//

static TIM_TypeDef* find_pin_tim(gpio_pin_t pin, uint_fast8_t *channel, gpio_af_t *af_code, rcc_periph_t *rcc) {
	uint_fast8_t ch = 4;
	gpio_af_t af = 0;
	rcc_periph_t TIMxEN = 0;
	TIM_TypeDef *TIMx = NULL;
EOF
for t in ${timers}; do
	printf "%s" "${template_4ch}" | sed -e "s|NNN|${t}|g"
done

cat << EOF
END:
	if (channel != NULL) {
		*channel = ch;
	}
	if (af_code != NULL) {
		*af_code = af;
	}
	if (rcc != NULL) {
		*rcc = TIMxEN;
	}
	return TIMx;
}
EOF
