#!/bin/sh

#timers="1 2 3 4 5 6 7 8 9 10 11 12 13 14"
# This is the order we check them to find the best sleep and uscounter timers
timers="6 7 8 11 13 14 9 12 10 5 3 4 2 1"
ports="A B C D E F G H I J K L M N O"

template="
//
// Timer NNN
#if defined(TIMNNN)
# if ! defined(SLEEP_ALARM_TIMER)
#  define SLEEP_ALARM_TIMER TIMER_NNN
# endif

# if SLEEP_ALARM_TIMER == TIMER_NNN
#  undef USE_TIMERNNN_PWM
#  define USE_TIMERNNN_PWM 0
#  define SLEEP_ALARM_TIM        TIMNNN
#  define SLEEP_ALARM_CLOCKEN    RCC_PERIPH_TIMNNN
#  define SLEEP_ALARM_IRQn       TIMNNN_IRQn
#  define SLEEP_ALARM_IRQHandler TIMNNN_IRQHandler
# elif ! defined(USCOUNTER_TIMER)
#  define USCOUNTER_TIMER TIMER_NNN
# endif

# if defined(USCOUNTER_TIMER) && USCOUNTER_TIMER == TIMER_NNN
#  undef USE_TIMERNNN_PWM
#  define USE_TIMERNNN_PWM 0
#  define USCOUNTER_TIM        TIMNNN
#  define USCOUNTER_CLOCKEN    RCC_PERIPH_TIMNNN
#  define USCOUNTER_IRQn       TIMNNN_IRQn
#  define USCOUNTER_IRQHandler TIMNNN_IRQHandler
# endif

# ifndef USE_TIMERNNN_PWM
#  if defined(PINID_TIMNNN_CH1)
#   define USE_TIMERNNN_PWM 1
#  else
#   define USE_TIMERNNN_PWM 0
#  endif
# endif

/*
# if USE_TIMERNNN_PWM && uHAL_USE_PWM
   DEBUG_CPP_MSG(\"Using timer NNN PWM\")
# endif
*/

#else
# undef USE_TIMERNNN_PWM
# define USE_TIMERNNN_PWM 0
#endif
"

cat <<-EOF
//
// Generated by ${0} on $(date)
//

//
// This is done so that we can set SLEEP_ALARM_TIMER to 0 to auto-select
#if SLEEP_ALARM_TIMER == TIMER_NONE
# undef SLEEP_ALARM_TIMER
#endif
//
// This is done so that SLEEP_ALARM_TIMER isn't auto-selected if we don't need
// it
#if ! uHAL_USE_HIBERNATE
# undef SLEEP_ALARM_TIMER
# define SLEEP_ALARM_TIMER TIMER_NONE
#endif

//
// This is done so that we can set USCOUNTER_TIMER to 0 to auto-select
#if USCOUNTER_TIMER == TIMER_NONE
# undef USCOUNTER_TIMER
#endif
//
// This is done so that USCOUNTER_TIMER isn't auto-selected if we don't need
// it
#if ! uHAL_USE_USCOUNTER
# undef USCOUNTER_TIMER
# define USCOUNTER_TIMER TIMER_NONE
#endif
EOF

for t in ${timers}; do
	printf "%s" "${template}" | sed "s|NNN|${t}|g"
done

port_template="
#ifndef DISABLE_PORTNNN_PWM
# define DISABLE_PORTNNN_PWM 0
#endif
#define HAVE_GPIO_PORTNNN_PWM (HAVE_GPIO_PORTNNN && ! DISABLE_PORTNNN_PWM)
"

for p in ${ports}; do
	printf "%s" "${port_template}" | sed "s|NNN|${p}|g"
done
